### ISSUE TITLE
Improve implementation of permute

### ISSUE THREAD

**Issue by thosou** [nordic-cad-tools/sw_cap_design_tool#5]
https://github.com/nordic-cad-tools/sw_cap_design_tool/blob/9cde0f00a1305a6d36b0796289be09daae339cc0/pyseeman/core.py#L787-L806

As a possible improvements, we should use itertools and product: https://docs.python.org/3/library/itertools.html#itertools.product

**Comment by denlar** [comment]
What would the benefits of this be? Readability or speed? Is speed important here?

Notice that a cascade of two topologies is not a simple product but requires different arithmetic on each of the topology object fields.

You're welcome to try to improve it but maybe it's more fun to spend the time on the real toolbox.

**Comment by thosou** [comment]
It is definitely not hi priority or mandatory change. It is certainly faster but not critical here.
It is just more pythonic!

**Comment by denlar** [comment]
But would it be possible at all given that it is not just a product

**Comment by denlar** [comment]
Fixed in 80e6097
