### ISSUE TITLE
Move plot_opt_contour in implementation class

### ISSUE THREAD

**Issue by thosou** [nordic-cad-tools/sw_cap_design_tool#7]
Hi @denlar,

Should we move the plot_opt_contour to the Implemetation class or at least add the method to the class?
It would behave the same as evaluate_loss and so on.

**Comment by denlar** [comment]
Hi @thosou ,
That would make good sense for the plot_opt_contour function. However, the plot_regulation cannot really be put in any class so one of the plot function would anyway have to be standalone. So maybe it is more intuitive if both plot function don't belong to a class.

I don't have a strong opinion on this one so you're welcome to make the change if you think it makes more sense.

**Comment by thosou** [comment]
I agree that plot_regulation cannot stand in a class. I think we should keep plot_opt_contour outside and have a method that calls this function. I will make a proposal :)

**Comment by denlar** [comment]
Sounds good!
