### ISSUE TITLE
Renaming of Ac to avoid conflict

### ISSUE THREAD

**Issue by thosou** [nordic-cad-tools/sw_cap_design_tool#8]
Hi @denlar,

I found a conflict of the cap multiplier and the cap area when renaming with lower case:
https://github.com/nordic-cad-tools/sw_cap_design_tool/blob/0be2b7fc527b97752a094080c5b64c880fa11693/pyseeman/core.py#L458

We should change the name Ac to something else like acap or area_cap, ...
We should probably have consistency with Asw as well.
What do you think?

**Comment by denlar** [comment]
Hi @thosou, I agree that area_cap and area_sw or something along those lines would be better!

**Comment by thosou** [comment]
ok. I will rename to area_cap and area_sw.

**Comment by thosou** [comment]
Fixed in 630dc132a674c504619f86c83aadaf07c7bd7f25
